### PR TITLE
Clickable url and customreport rename

### PR DESCRIPTION
**Pull request by peterjaap**
Usage of clickable URL;

```
SELECT entity_id, `main_table`.increment_id,'*/sales_order/view/order_id/entity_id' as clickable_url FROM `sales_flat_order` AS `main_table`
```
The clickable_url column will be skipped while generating the grid.

The '*/sales_order/view/order_id/entity_id' part will be used to generate the grid. The last part behind the / will be used to look for the column name in the query (entity_id). The part before that (id) will be used as the field parameter in the get query. The rest will be used for the first argument for getUrl().

### CODE REVIEW

**Comment by kalenjordan** [comment]
I'm sure I don't need to test this given that the great @peterjaap did it!

**Comment by peterjaap** [comment]
Lol that might be too much credit but we'll see :sunglasses:

**Comment by MarcusWolschon** [comment]
So 1 clickable URL is possible but there is no way to make more columnd clickable?
A good step forward.

**Comment by MarcusWolschon** [comment]
Your exact example doesn't seem to work here.
Is there some specific version of "custom-reports" required?

**Comment by peterjaap** [comment]
Nope it's in the master. Make sure you're not using an alias for the field referenced in clickable_url.

**Comment by MarcusWolschon** [comment]
Yes, I needed a special version.
I needed to update to the latest git master.
There was no new (stable) release of the "custom-reports" project.

The URLs are clickable but a right click to open them in a new tab doesn't work because they are not regular HTML links.

**Pull request merged**
