### PR TITLE
Fixed clickable URLs for columns, code by @sreichel

### LINKED ISSUE #51: Clilckable URL does not work in some cases

### PR DESCRIPTION
**Pull request by peterjaap**
Fixed clickable URLs for columns, code by @sreichel, also added hide option and updated README.

This fixes #51 

Thanks @sreichel

### CODE REVIEW

**Comment by peterjaap** [comment]
@kalenjordan, can you check this out?

**Comment by kalenjordan** [comment]
@peterjaap genius - on a high level love the idea.  Took a quick peek at the code.  You want a deep dive code review?

**Comment by peterjaap** [comment]
I did, works perfectly

**Comment by kalenjordan** [comment]
Sweet anything you need from me?  @peterjaap

**Comment by peterjaap** [comment]
No it just needs a version bump, will try and get around to it later this
week.

**Pull request merged**
